### ISSUE TITLE
Tag a release version

### ISSUE THREAD

**Issue by MaxGfeller** [killbill/killbill-client-php#13]
I'm not sure about the release version schema you've decided now, but it would be cool if you could tag a version. It is [not possible](https://getcomposer.org/doc/04-schema.md#minimum-stability) to require a `dev-master` version from Packagist if you've set your `minimum-stability` to `stable`.

**Comment by pierre** [comment]
0.0.1 released!

https://packagist.org/packages/killbill/killbill-client#0.0.1

**Comment by MaxGfeller** [comment]
Yay, thank you!
