### ISSUE TITLE
Create a payment for invoice

### ISSUE THREAD

**Issue by julienfastre** [killbill/killbill-client-php#24]
In the [PR 23](https://github.com/killbill/killbill-client-php/pull/23) a method `Invoice::getPayments` was created. 

I suggest to add the counterpart method `Invoice::createPayment`

I propose the following signature:

```
    /**
     * 
     * @param string $purchasedAmount
     * @param string $paymentMethodId
     * 
     * @return InvoicePayment
     */
    public function createPayment($purchasedAmount = null, $paymentMethodId = null)
```

Do you agree with this feature ?

**Comment by pierre** [comment]
👍 for the feature but how about creating `InvoicePayment::create` instead? That way, all of the various fields would be supported, like external keys, payment method id, etc. (see https://github.com/killbill/killbill/blob/7c0d134b6f56490b28f93a973235755a1ac371ed/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/InvoiceResource.java#L642).

This is how the Ruby client does it: https://github.com/killbill/killbill-client-ruby/blob/562ab23172966f377639348bcc489ba34b656f78/lib/killbill_client/models/invoice_payment.rb#L39-L51

**Comment by julienfastre** [comment]
@pierre You mean: 

```
$invoicePayment = new InvoicePayment($logger);
$invoicePayment->setTargetInvoiceId($invoiceId);
$invoicePayment->setPaymentMethodId($paymentMethod->getId());
// ...
$created = $invoicePayment::create(false, $user, $comment, $reason);
```

It sounds to be consistent with the rest of this library.

The envelope will be:

```
    /**
     * @param boolean     $externalPayment If the payment 
     * @param string|null   $user    User requesting the creation
     * @param string|null   $reason  Reason for the creation
     * @param string|null   $comment Any addition comment
     * @param string[]|null $headers Any additional headers
     *
     * @return Account|null The newly created payment method
     */
    public function create($externalPayment = false, $user = null, $reason = null, $comment = null, $headers = null)
```

To be sure that I fully understand (I am quite new in Killbill world), an _external payment_ is a payment made outside of the kill bill platform. Am I right ? It means that kill bill should consider the invoice paid, or the account charged, without triggering a payement on an external platform. Could you explain me this concept ?

**Comment by pierre** [comment]
> It sounds to be consistent with the rest of this library.

Yes, that looks better. I suggest going through the tests to see how current calls are used.

> To be sure that I fully understand (I am quite new in Killbill world), an external payment is a payment made outside of the kill bill platform. Am I right ? It means that kill bill should consider the invoice paid, or the account charged, without triggering a payement on an external platform. Could you explain me this concept ?

An external payment is associated with the built-in external payment method, which is typically used to record checks that the customer sends you (see how it is used in the 5' tutorial: http://docs.killbill.io/latest/userguide_subscription.html#five-minutes-create-account).

If you have further questions, please reach out to the mailing-list instead.

**Comment by pierre** [comment]
The client is now auto-generated.
