### ISSUE TITLE
[Bug] Unrecognized field "isNotifiedForInvoices"

### ISSUE THREAD

**Issue by LamDoan2712** [killbill/killbill-client-php#34]
I am using killbill-client-php with killbill 0.20 and trying test with your example.

I got error like that : 

{"className":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException","code":null,"message":"Unrecognized field \"isNotifiedForInvoices\" (class org.killbill.billing.jaxrs.json.AccountJson), not marked as ignorable (26 known properties: \"firstNameLength\", \"paymentMethodId\", \"isMigrated\", \"accountId\", \"auditLogs\", \"name\", \"billCycleDayLocal\", \"accountBalance\", \"currency\", \"externalKey\", \"accountCBA\", \"country\", \"referenceTime\", \"timeZone\", \"locale\", \"email\", \"address1\", \"parentAccountId\", \"notes\", \"isPaymentDelegatedToParent\", \"city\", \"phone\", \"state\", \"postalCode\", \"company\", \"address2\"])\n at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 1, column: 567] (through reference chain: org.killbill.billing.jaxrs.json.AccountJson[\"isNotifiedForInvoices\"])","causeClassName":null,"causeMessage":null,"stackTrace":[]}

**Comment by pierre** [comment]
The client is now compatible with 0.20.x.
