### ISSUE TITLE
[Bug] Tenant client causes undefined variable notice

### ISSUE THREAD

**Issue by ko2in** [killbill/killbill-client-php#43]
When using the Tenant client, the PHP undefined variable notice appears as below:
```
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: apiKey

Filename: src/Tenant.php

Line Number: 36
```
The variables `apiKey` and `apiSecret` are protected from the inheritance class. It should use `getApiKey` and `getApiSecret` methods from the parent class instead.

**Comment by GregOriol** [comment]
@ko2in Are you using the v0.18.x version? Not sure there will be updates on that version as it is older now (or can you make a PR?) Otherwise, it would be better to upgrade to v0.20 to get the more modern code.

**Comment by ko2in** [comment]
@GregOriol , here's the version from my composer.json.
```
"killbill/killbill-client": "^0.2.0"
```

**Comment by GregOriol** [comment]
@ko2in That's indeed a quite old version!

**Comment by GregOriol** [comment]
@pierre Maybe it'll be time to make a new release for v0.20.x?

**Comment by pierre** [comment]
@GregOriol Indeed, I need to remember how it works with Composer... It has been a while... 😬

**Comment by pierre** [comment]
@ko2in @GregOriol 0.3.0 has been released. 

> @GregOriol Indeed, I just need to remember how it works with Composer... It has been a while... 😬

Future @pierre: creating the Github release is enough, Packagist will auto-update (webhook in place).

**Comment by ko2in** [comment]
@pierre Thank you very much. I've updated to version 0.3.0. I think README.md doesn't reflect the new version. The example for the getting started section has some errors.
```
use Killbill\Client\Api\AccountApi;
use Killbill\Client\Api\TenantApi;
use Killbill\Client\Model\Account;
use Killbill\Client\Model\Tenant;

// Killbill configuration
$config = Configuration::getDefaultConfiguration();
```
I got the errors with the above example. I've looked into the source files and the namespaces are not correct as defined in the actual classes. The correct usage should be:
```
use Killbill\Client\Swagger\Api\AccountApi;
use Killbill\Client\Swagger\Api\TenantApi;
use Killbill\Client\Swagger\Model\Account;
use Killbill\Client\Swagger\Model\Tenant;

// Killbill configuration
$config = Killbill\Client\Swagger\Configuration::getDefaultConfiguration();
```
And it works fine as expected. Should I close this issue now?

**Comment by GregOriol** [comment]
@ko2in Thanks, I just created a PR to fix that
