### ISSUE TITLE
tests fail: Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by karser** [killbill/killbill-client-php#49]
https://circleci.com/gh/killbill/killbill-client-php/89
![image](https://user-images.githubusercontent.com/1675033/72210338-75084f00-34c2-11ea-8f6e-7ae5bf80de0e.png)

**Comment by pierre** [comment]
Wasn't it fixed by https://github.com/killbill/killbill-client-php/pull/44?

**Comment by karser** [comment]
Nope, CI didn't even get to the tests execution
https://github.com/killbill/killbill-client-php/pull/48

**Comment by karser** [comment]
@pierre sorry, my bad. My branch is old
